import { IUser } from "../model/types";
import mockImage from "/public/icons/mockImage.webp";

export const mockRoute = [
  {
    id: 1,
    routeFrom: "Самара 3 проезд 44",
    routeBefore: "Самара Советской Армии, 134",
  },
  {
    id: 2,
    routeFrom: "Самара",
    routeBefore: "Екатеринбург",
  },
  {
    id: 3,
    routeFrom: "Самара",
    routeBefore: "Москва",
  },
  {
    id: 4,
    routeFrom: "Самара",
    routeBefore: "Питер",
  },
  {
    id: 5,
    routeFrom: "Самара",
    routeBefore: "Сахалин",
  },
];

export const mockUsers: IUser[] = [
  {
    id: 1,
    imageSrc: mockImage,
    nameDriver: "Александр",
    status: "Доступен",
    typeCar: "Легковой",
    capacity: "1 тонна",
    experience: "3 года",
    car: "",
    numberCar: "Х1632",
  },
  {
    id: 2,
    imageSrc: mockImage,
    nameDriver: "Иван",
    status: "Назначенный",
    typeCar: "Грузовой",
    capacity: "5 тонн",
    car: "",
    experience: "2 года",
    numberCar: "Х2345",
  },
  {
    id: 3,
    imageSrc: mockImage,
    nameDriver: "Мария",
    status: "Активный",
    typeCar: "Легковой",
    capacity: "1.5 тонны",
    car: "",
    experience: "4 года",
    numberCar: "Х3456",
  },
  {
    id: 4,
    imageSrc: mockImage,
    nameDriver: "Дмитрий",
    status: "Отменённый",
    typeCar: "Грузовой",
    capacity: "3 тонны",
    car: "",
    experience: "1 год",
    numberCar: "Х4567",
  },
  {
    id: 5,
    imageSrc: mockImage,
    nameDriver: "Анна",
    status: "Доступен",
    typeCar: "Легковой",
    capacity: "1 тонна",
    car: "",
    experience: "5 лет",
    numberCar: "Х5678",
  },
  {
    id: 6,
    imageSrc: mockImage,
    nameDriver: "Сергей",
    status: "Назначенный",
    typeCar: "Грузовой",
    car: "",
    capacity: "7 тонн",
    experience: "3 года",
    numberCar: "Х6789",
  },
  {
    id: 7,
    imageSrc: mockImage,
    nameDriver: "Ольга",
    status: "Активный",
    typeCar: "Легковой",
    car: "",
    capacity: "1 тонна",
    experience: "2 года",
    numberCar: "Х7890",
  },
  {
    id: 8,
    imageSrc: mockImage,
    nameDriver: "Павел",
    status: "Отменённый",
    typeCar: "Грузовой",
    car: "",
    capacity: "5 тонн",
    experience: "4 года",
    numberCar: "Х8901",
  },
  {
    id: 9,
    imageSrc: mockImage,
    nameDriver: "Елена",
    status: "Доступен",
    typeCar: "Легковой",
    car: "",
    capacity: "1.5 тонны",
    experience: "6 лет",
    numberCar: "Х9012",
  },
  {
    id: 10,
    imageSrc: mockImage,
    nameDriver: "Тимур",
    status: "Назначенный",
    typeCar: "Грузовой",
    car: "",
    capacity: "8 тонн",
    experience: "3 года",
    numberCar: "Х0123",
  },
  {
    id: 11,
    imageSrc: mockImage,
    nameDriver: "Артур",
    status: "Активный",
    typeCar: "Легковой",
    car: "",
    capacity: "1 тонна",
    experience: "2 года",
    numberCar: "Х1234",
  },
  {
    id: 12,
    imageSrc: mockImage,
    nameDriver: "Наталья",
    status: "Отменённый",
    typeCar: "Грузовой",
    car: "",
    capacity: "3 тонны",
    experience: "1 год",
    numberCar: "Х2346",
  },
  {
    id: 13,
    imageSrc: mockImage,
    nameDriver: "Кирилл",
    status: "Доступен",
    typeCar: "Легковой",
    car: "",
    capacity: "1 тонна",
    experience: "5 лет",
    numberCar: "Х3457",
  },
  {
    id: 14,
    imageSrc: mockImage,
    nameDriver: "Даша",
    status: "Назначенный",
    typeCar: "Грузовой",
    car: "",
    capacity: "6 тонн",
    experience: "120 года",
    numberCar: "Х4568",
  },
];
